### PR TITLE
Fix related bugs and add animation and background in ios

### LINKED ISSUE #5: Date Picker Date and Time input simultaneously
Hey is it possible to get this date-picker to show date and time simultaneously as follows:
Screenshot 2020-08-02 at 14 15 37
I'm currently getting date and time sequentially presented. Tried a few formats but mostly getting the app crashing when I thinker with those.
& on a related note: is it possible to hide the 'date preview' at the top?
Thanks!

### LINKED ISSUE #6: Time minutes preview broken on iOS?
I'm feeding following date into the options
`date: "2020-08-02T16:00:00.000Z"`
The pickers seem to be initialising correctly, except the preview time seems to have an offset in minutes and minutes are not updating when I change them in the time picker (date and hours are updating correctly as I change them).
IMG_2916
IMG_2917
The date that gets returned also reflects the correct date and time (including minutes) chosen by the pickers.
Am I doing something wrong or is something broken on the iOs end?

```
iOS 13.5.1
"@capacitor-community/date-picker": "^0.1.0",
"@capacitor/core": "^2.4.0",
"@capacitor/ios": "^2.4.0",
```
Thanks

### LINKED ISSUE #7: Android initialising AM for PM Time
When initialising following date on android 
`
mode: 'dateAndTime',
date: '2020-08-02T16:00:00.000Z', 
is24h: true
`
Date is correct but it seems to transform the PM time (16) to AM. It does so with is24h set to true and false.
Screenshot 2020-08-02 at 15 16 10
Screenshot 2020-08-02 at 15 16 30

Getting to that date string by calling .toISOString() on a date as seen in the example. iOS seems to be handling this correctly (except the preview minutes issue flagged in https://github.com/capacitor-community/date-picker/issues/6)
Is that a wrong way of passing on the date or is something broken?

`
Android 9.0
"@capacitor-community/date-picker": "^0.1.0",
"@capacitor/core": "^2.4.0",
"@capacitor/android": "^2.4.0",`

Thanks

### LINKED ISSUE #8: Add backdrop on iOS when date picker is open
it would be a nice to add a background for inactive part so that the user can see where the date picker ends:

React_Native_DatePicker_Modal_Component_for_iOS_Android

### LINKED ISSUE #9: Add slide animation for iOS
It would be nice to add slide up/down animation when date picker appears and disappears.

### PR DESCRIPTION
**Pull request by danielprrazevedo**
close #6
close #7 

Add requested features in this PR and update readme.md
close #5 
close #8 
close #9

### CODE REVIEW

**Comment by danielprrazevedo** [comment]
Add requested features in this PR and update readme.md
closes: #5 
closes: #8 
closes: #9

**Comment by joplaete** [comment]
Thanks for these! Just tested all good :)

**Comment by joplaete** [comment]
Thanks for these! All good except one (new) issue: on android it seems like it's not returning the newly selected date, but rather the input date, the time comes through correctly though (and also initialises correctly). Are you seeing the same?

**Comment by danielprrazevedo** [comment]
@joplaete I did some tests and I couldn't reproduce the problem, here it is working normally. However I found a problem when I use the default formats that are returning the wrong timezone on both platforms.

**Comment by joplaete** [comment]
@danielprrazevedo thanks for looking into it. I do think the issue still exists for android and was able to repro it on the example by adding the following before presenting the DatePicker
`options.date = new Date("2020-10-14 10:25:00.000").toISOString();
    return DatePicker.present(options);`
The example works out of the box but to me it seems when you initialise the android picker with a date, no matter what date you change it to in the DatePicker, it will return that date you pass in. The time does seem to behave correctly and gets updated to what gets picked.
(on ios both date and time update correctly even when initialised)
Screenshot 2020-10-16 at 15 02 45
Screenshot 2020-10-16 at 15 03 01

On a sidenote, with the same example, passing in 
options.date = new Date("2020-10-14 10:25:00.000").toISOString();
Both android and ios pickers initialise at the time at 8:25, it looks like the picker is initialising it taking the local timezone into account? It'd expect it to initialise the date as I pass it in, currently I'd need to pre-adjust it to show correctly?
Screenshot 2020-10-16 at 15 02 04


Thanks

**Comment by roxteddy** [comment]
Hi @joplaete ! About the sidenote :

 [Date.prototype.toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) output includes timezone (YYYY-MM-DDTHH:mm:ss.sssZ)

You may want to give the DatePicker a timezone agnostic format. I use momentJS to handle and format dates on my project.

Also be careful, the DatePicker does not expect an ISO string but a Java [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) as discussed in [this issue](https://github.com/capacitor-community/date-picker/issues/14)

here's my implementation as an example :


    private pickDate(): Promise<moment.Moment> {
        const isoFormat = 'YYYY-MM-DD';
        const format= 'yyyy-MM-dd';
        const date = moment(this.publishingDate).format(isoFormat);
        const min = moment().format(isoFormat);

        return new Promise((resolve, reject) => {
            this.capacitorPlugins.datePicker.present({
                date,
                format,
                min,
                mode: 'date',
                theme: 'light'
            }).then((result) => {
                if (result.value) {
                    let newDate = moment(result.value, isoFormat);
                    resolve(moment(this.publishingDate)
                        .year(newDate.year())
                        .month(newDate.month())
                        .date(newDate.date()));
                } else {
                    reject('no value');
                }
            }, reason => reject(reason));
        });
    }

    private pickTime(): Promise<moment.Moment> {
        const format= 'HH:mm';
        const date = moment(this.publishingDate).format(format);

        return new Promise((resolve, reject) => {
            this.capacitorPlugins.datePicker.present({
                date,
                format,
                mode: 'time',
                theme: 'light'
            }).then((result) => {
                if (result.value) {
                    let newDate = moment(result.value, format);
                    resolve(moment(this.publishingDate)
                        .hour(newDate.hour())
                        .minute(newDate.minute())
                        .second(newDate.second()));
                } else {
                    reject('no value');
                }
            }, reason => reject(reason));
        });
    }

**Comment by joplaete** [comment]
thanks for this @roxteddy 
Have you tried this on iOs when trying to provide dateAndTime simultaneously?
I've tried feeding it a few formats like "2020-10-28T09:00:00" but I will always get 
`[error] - Error: Uncaught (in promise): Error: Failed to parse date`
Unless I provide it moment.toISOString() which generates 2020-10-28T09:00:00.000Z I cannot get it to work.

**Pull request merged**
